config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'contacts#index'
  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, execpt: [:index, :show]
  def index
    @contacts = Contact.all.order(:name)
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = current_user.contacts.create(contact_params)
    if @contact.save
      redirect_to contacts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @contact.update_attributes(contact_params)
      redirect_to @contact
    else
      render :edit
    end
  end

  def destroy
    @contact.delete
    redirect_to contacts_path
  end

  private

    def contact_params
      params.require(:contact).permit(:name, :email, :phone_number, :avatar)
    end

    def set_contact
      @contact = Contact.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for @contact, :url => contacts_path, :html => { :multipart => true }  do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :phone_number %>
  <%= f.input :avatar %>
  <%= f.button :submit %>
<% end %>

app/views/contacts/edit.html.erb
<h1>Edit Contact</h1>

<%= render 'form' %>

<%= link_to 'Cancel', contact_path(@contact.id) %>

app/views/contacts/index.html.erb
<h1>All Contacts</h1>

<% @contacts.each do |contact| %>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Contact</h3>
  </div>
  <div class="panel-body">
  <%= image_tag contact.avatar.url(:thumb) %>
    <dl>
      <dt>Name:</dt>
      <dd><%= contact.name %></dd>
      <dt>Email:</dt>
      <dd><%= contact.email %></dd>
      <dt>Phone Number:</dt>
      <dd><%= contact.phone_number %></dd>
      <dt><%= link_to 'See Contact', contact_path(contact.id), class: 'btn btn-success' %></dt>
    </dl>
  </div>
</div>
<% end %>
<%= link_to 'New Contact', new_contact_path, class: 'btn btn-warning' %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Cancel', contacts_path %>

app/views/contacts/show.html.erb
<h1>Contact</h1>
<div class="panel panel-success">
  <div class="panel-heading">
    <h1 class="panel-title text-center">Contact Info</h1>
  </div>
  <div class="panel-body">
  <%= image_tag @contact.avatar.url(:thumb) %>
    <dl>
      <dt>Name:</dt>
      <dd><%= @contact.name %></dd>
      <dt>Email:</dt>
      <dd><%= @contact.email %></dd>
      <dt>Phone Number:</dt>
      <dd><%= @contact.phone_number %></dd>
      <dt>
        <%= link_to 'Edit', edit_contact_path(@contact.id), class: 'btn btn-success' %>
        <%= link_to 'Back', contacts_path, class: 'btn btn-success' %>
      </dt>
    </dl>
    <%= link_to 'Delete', contact_path(@contact.id), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Contacts Book</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Contacts', root_path %></li>
        <li><a href="#">Link</a></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.email, edit_user_registration_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddressBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<div class="container">
  <% if notice %><div class="alert alert-info"><%= notice %></div><% end %>
  <% if alert %><div class="alert alert-info"><%= alert %></div><% end %>
  <%= yield %>
</div>
</body>
</html>